Todo.Api/Models/ErrorViewModel.cs
using System;

namespace Todo.Api.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Todo.Api/Models/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Todo.Api.Models
{
    public class LoginViewModel
    {
        [Required]
        public string UserName { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        //[Display(Name = "Remember me?")]
        //public bool RememberMe { get; set; }

    }
}

Todo.Api/Models/NavbarViewComponent.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Todo.Api.Service.Interface;

namespace Todo.Api.Models
{
    public class NavbarViewComponent: ViewComponent
    {
        private INavbarService _navbarService;

        public NavbarViewComponent(INavbarService navbarService)
        {
            _navbarService = navbarService;
        }

        // GET: Navbar
        [Authorize]
        public IViewComponentResult Invoke()
        {
            var navabarViewModel = _navbarService.GetNavbarItems(); 
            return View(navabarViewModel);
        }
    }
}

Todo.Api/Models/TodoViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Todo.Api.Models
{
    public class TodoViewModel
    {
        public int Id { get; set; }
        public string CreationDate { get; set; }
        [Required]
        public string Description { get; set; }
        public string ModificationDate { get; set; }
        public bool Status { get; set; }
        public int ListaTodoId {get;set;}
    }
}

Todo.Api/Controllers/AccountController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Todo.Api.Models;
using Todo.Api.Service.Interface;

namespace Todo.Api.Controllers
{
    public class AccountController : Controller
    {
        private ILoginService _loginService;
        
        public AccountController(ILoginService loginService)
        {
            _loginService = loginService;
        }

        // GET: Account
        [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View(new LoginViewModel());
        }

        // POST: /Account/Login
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Login(LoginViewModel model, string returnUrl)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var users = _loginService.GetUsers();

            if (users.Any(p => p.user == model.UserName && p.password == model.Password && p.status))
            {
                var identity = new ClaimsIdentity(new[] { new Claim(ClaimTypes.Name, model.UserName), }, CookieAuthenticationDefaults.AuthenticationScheme);
                var authProperties = new AuthenticationProperties
                {
                    AllowRefresh = true,
                    //IsPersistent = model.RememberMe                    
                };
                await HttpContext.SignInAsync(
                    CookieAuthenticationDefaults.AuthenticationScheme,
                    new ClaimsPrincipal(identity),
                    authProperties);
                return RedirectToAction("Index", "Todo");
            }
            else
            {
                ModelState.AddModelError("", "Invalid login attempt.");
                return View(model);
            }
        }

        //POST: /Account/LogOff
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> LogOff()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Login", "Account");
        }
    }
}

Todo.Api/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Todo.Api.Models;

namespace Todo.Api.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                return View();
            }
            else
                return RedirectToAction("Login", "Account");
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Todo.Api/Controllers/TodoController.cs
using Microsoft.AspNetCore.Mvc;
using Todo.Api.Service.Interface;

namespace Todo.Api.Controllers
{
    public class TodoController : Controller
    {
        private ITaskService _taskService;

        public TodoController(ITaskService taskService)
        {
            _taskService = taskService;
        }

        public IActionResult Index()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return null;
            }

            return View();
        }

        [HttpPost]
        public bool AddNewTask(string description)
        {
            return _taskService.AddNewTask(User.Identity.Name, description);
        }

        [HttpPut]
        public bool EditTask(int idTask, string newDescription)
        {
            return _taskService.EditTask(User.Identity.Name, idTask, newDescription);
        }

        [HttpDelete]
        public bool DeleteTask(int idTask)
        {
            return _taskService.DeleteTask(User.Identity.Name, idTask);
        }

        [HttpGet]
        public JsonResult GetListTaskItem()
        {
           return Json(_taskService.GetListTaskItem(User.Identity.Name));
        }

        [HttpPut]
        public bool MarkAsDone(int idTask, bool done)
        {
            return _taskService.MarkAsDone(idTask, User.Identity.Name, done);
        }


   }
}

Todo.Api/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Todo.Api/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Todo.Api/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

Todo.Api/Views/Shared/Components/Navbar/Default.cshtml
@model IEnumerable<Todo.Api.Model.Navbar>

<script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>

<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>

        <div class="collapse navbar-collapse">
            <!--LEFT ITEMS-->
            <ul class="nav navbar-nav">

                @*TODO: SHOULD BE A METHOD(htmlhelper) 'start -> end' *@
                @*start*@

                @foreach (var item in Model.Where(c => c.RighSide.Equals(false) && c.Status))
                {
                    if (item.IsParent == false && item.ParentId == 0)
                    {
                        <li>
                            <a class="@item.Activeli" href="@Url.Action(item.Action, item.Controller)">
                                <span class="@item.ImageClass" title="@item.Tooltip"></span>
                                @item.NameOption
                            </a>
                        </li>
                    }
                    else
                    {
                        <li>
                            @if (item.IsParent == true && item.ParentId == 0)
                            {
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <span class="@item.ImageClass" title="@item.Tooltip"></span>
                                    @item.NameOption
                                    <span class="caret"></span>
                                </a>
                            }
                            <ul class="dropdown-menu">
                                @foreach (var child in Model.Where(p => p.ParentId == item.Id && p.Status))
                                {
                                    if (child.IsParent == true)
                                    {
                                        <li>
                                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">@child.NameOption <b class="caret caret-right"></b></a>
                                            <ul class="dropdown-menu">
                                                @foreach (var child2 in Model.Where(p => p.ParentId == child.Id))
                                                {
                                                    <li>
                                                        @Html.AntiForgeryToken()
                                                        <a href="@Url.Action(child2.Action, child2.Controller)">
                                                            @child2.NameOption
                                                        </a>
                                                    </li>
                                                }
                                            </ul>
                                        </li>
                                    }
                                    else
                                    {
                                        <li>
                                            @Html.AntiForgeryToken()
                                            <a href="@Url.Action(child.Action, child.Controller)">
                                                <span class="@child.ImageClass"></span>
                                                @child.NameOption
                                            </a>
                                        </li>
                                    }
                                }

                            </ul>
                        </li>
                    }
                }
            </ul>

            @*end*@

            <!--RIGHT ITEMS-->
            <ul class="nav navbar-nav navbar-right">

                @*TODO: SHOULD BE A METHOD(htmlhelper) 'start -> end' *@
                @*start*@

                @foreach (var item in Model.Where(c => c.RighSide.Equals(true) && c.Status))
                {
                    if (item.IsParent == false && item.ParentId == 0)
                    {
                        <li>
                            <a class="@item.Activeli" href="@Url.Action(item.Action, item.Controller)">
                                <span class="@item.ImageClass" title="@item.Tooltip"></span>
                                @item.NameOption
                            </a>
                        </li>
                    }
                    else
                    {
                        <li>
                            @if (item.IsParent == true && item.ParentId == 0)
                            {
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <span class="@item.ImageClass" title="@item.Tooltip"></span>
                                    @item.NameOption
                                    <span class="caret"></span>
                                </a>
                            }
                            <ul class="dropdown-menu">
                                @foreach (var child in Model.Where(p => p.ParentId == item.Id && p.Status))
                                {
                                    if (child.IsParent == true)
                                    {
                                        <li>
                                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">@child.NameOption <b class="caret caret-right"></b></a>
                                            <ul class="dropdown-menu">
                                                @foreach (var child2 in Model.Where(p => p.ParentId == child.Id))
                                                {
                                                    <li>
                                                        @Html.AntiForgeryToken()
                                                        <a href="@Url.Action(child2.Action, child2.Controller)">
                                                            @child2.NameOption
                                                        </a>
                                                    </li>
                                                }
                                            </ul>
                                        </li>
                                    }
                                    else
                                    {
                                        <li>
                                            @Html.AntiForgeryToken()
                                            <a href="@Url.Action(child.Action, child.Controller)">
                                                <span class="@child.ImageClass"></span>
                                                @child.NameOption
                                            </a>
                                        </li>
                                    }
                                }
                                <li>
                                    <form action="/Account/LogOff" method="post">
                                        @Html.AntiForgeryToken()
                                        <button class="btn btn-default col-lg-12"
                                                style="border:hidden;text-align:left;">
                                            <span class="glyphicon glyphicon-off" style="margin-left:5%; font-size:110%;">&nbsp; @User.Identity.Name</span>
                                        </button>
                                    </form>
                                </li>
                            </ul>
                        </li>
                    }
                }

                @*end*@

            </ul>
        </div><!--/.nav-collapse -->
    </div>
</div>

Todo.Api/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>

    <link rel="stylesheet" href="~/css/navbar.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/font-awesome-5.5.0.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/Toastr/css/Toastr.min.css" asp-append-version="true"/>

</head>
<body>
    @await Component.InvokeAsync("Navbar") @*TO REPLACE @Html.Action("Navbar", "NavBar")*@
    <br />
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
    <script src="~/js/navbar.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/modernizr/modernizr-2.8.3.js" asp-append-version="true"></script>
    <script src="~/lib/Toastr/js/Toastr-v2.1.3.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js" asp-append-version="true"></script>
    <script src="~/js/Util.js" asp-append-version="true"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

Todo.Api/Views/Todo/Index.cshtml
@{
    ViewBag.Title = "Task list";
}

<script src="~/js/DataTables/jquery.dataTables.js" asp-append-version="true"></script>
<script src="~/js/TodoTask.js" asp-append-version="true"></script>

<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/DataTables/jquery.dataTables.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
<link rel="stylesheet" href="~/images/sort_asc.png" asp-append-version="true" />
<link rel="stylesheet" href="~/images/sort_asc_disabled.png" asp-append-version="true" />
<link rel="stylesheet" href="~/images/sort_both.png" asp-append-version="true" />
<link rel="stylesheet" href="~/images/sort_desc.png" asp-append-version="true" />
<link rel="stylesheet" href="~/images/sort_desc_disabled.png" asp-append-version="true" />

<style>
    /*used to guarantee headers in datatables won't wrap text*/
    .clsNoWrap {
        white-space: nowrap
    }
    th {
        text-align: center
    }
    td {
        text-align: center;
        vertical-align: middle;
    }

    .taskDone {
        background-color: #C5E3BF !important;
    } 

</style>
<br />

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default container-fluid">
            <div class="panel-heading row">
                <div class="col-md-8">
                    <span style="font-size:large;">
                        Welcome '<span style="font-weight:bold;">@User.Identity.Name</span>', your TODO task list:
                    </span>
                </div>
                <div class="col-md-4 text-right">
                    <button class="btn btn-default" data-toggle="modal" data-target="#AddEditTaskModal" title="Add a new Task" onclick="AddTask();">
                        <span class="glyphicon glyphicon-plus" style="color:green;"></span>
                    </button>
                </div>
            </div>
            <div class="panel-body">
                <table id="TaskListDataTable" class="display" style="width:100%">
                    <thead>
                        <tr>
                            <th width="5%"></th>
                            <th >Done</th>
                            <th class="clsNoWrap">Creation Date</th>
                            <th>Description</th>
                            <th class="clsNoWrap">Modification Date</th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@*MODAL*@
<div id="AddEditTaskModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title titleHeaderModal"></h4>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label for="comment">Description:</label>
                    <textarea id="txtDescription" class="form-control" rows="5" required></textarea>
                </div>
            </div>
            <div class="modal-footer">
                <button class="btn btn-success btnTaskEvent"></button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>